### ISSUE TITLE
The white-box explannation of CLS token

### ISSUE THREAD

**Issue by ngkel** [Ma-Lab-Berkeley/CRATE#10]
As I read the paper, the interpretation of MSSA and ISTA component for compression and sparsification of token representation are quite clear to me. However, I'm not so sure about the role and interpretation of the $z^l_{[CLS]}$ in each layer. I don't quite understand how $z^l_{[CLS]}$ affects the compression and sparsification and how it is transformed in each layer.

**Comment by DruvPai** [comment]
After it is added, it is just another token. It gets compressed/sparsified alongside the rest. The initialization is trained such that the class token compresses alongside the tokens which are relevant for classification and thus have semantic meaning (as one can see in our segmentation paper: https://arxiv.org/abs/2308.16271).
