### ISSUE TITLE
How CREAT differs from Transformer

### ISSUE THREAD

**Issue by moon2yue** [Ma-Lab-Berkeley/CRATE#11]
Thank you for your work. I have a question that may seem naive, namely where is your code mainly different from a classic Transformer.

**Comment by LeslieTrue** [comment]
Basically, there are two major differences. 

1.  Attention block: CRATE doesn't need separate Q, K, V matrices. We instead use a unified mapping denoted as $U_{[K]} Z$ inside the attention. 
2. Nonlinearity: CRATE uses an ISTA block to do sparsification. The role of ISTA is similar to an MLP in normal transformers.
