### ISSUE TITLE
Experiment on Diffusion Models

### ISSUE THREAD

**Issue by yuzheyao22** [Ma-Lab-Berkeley/CRATE#15]
Thanks for your inspiring work! I am especially interested in the structured denoising and structured diffusion section. However, I couldn not find the experiment results related to this part in the paper. Would you release in the future?

**Comment by DruvPai** [comment]
Hi,
Actually in the paper we use the formalism of diffusion models to motivate an autoencoder design. We don't use this autoencoder for diffusion models, though this could be some great future work. We have experiments designed for feature learning/autoencoding in the paper. Does this answer your question?
