### ISSUE TITLE
Can this be applied to languages?

### ISSUE THREAD

**Issue by ElrondL** [Ma-Lab-Berkeley/CRATE#20]
Good job @ CPAL!

**Comment by LeslieTrue** [comment]
Thanks! Yes, it's doable on languages and we've trained some models for i.e. masked language modeling. We've reported the results in our journal version.[https://arxiv.org/abs/2311.13110]( https://arxiv.org/abs/2311.13110 ). Also feel free to reach out offline!

**Comment by ElrondL** [comment]
Sure ^_^! Would be great if you could add documentations to the code you already have here and also provide short tutorials on how to use CRATE for language models. That would make the adaptability of your work even greater !
