### ISSUE TITLE
computing rate reduction in CRATE

### ISSUE THREAD

**Issue by heeseokjung** [Ma-Lab-Berkeley/CRATE#28]
@DruvPai  Thank you for sharing codes!

I would really appreciate it if you could share the code to compute $R(Z)$, $R^c(Z)$ in this CRATE code base.

Specifically, I want to reproduce the results in Fig. 3, Fig. 4. a, along with $R(Z)$.

Thank you for your help.

**Comment by LeslieTrue** [comment]
Hi, please check vis_utils/crate_hook.py
We provide example code for visualizing CRATE_small. Remark that the released checkpoint is different from the one we used in our manuscripts, hence the plots might be a little bit different.
